"""catalogue_chants

Revision ID: a1b2c3d4e5f6
Revises: e1f2a3b4c5d6
Create Date: 2026-05-29
"""
from alembic import op
import sqlalchemy as sa

revision = 'a1b2c3d4e5f6'
down_revision = 'e1f2a3b4c5d6'
branch_labels = None
depends_on = None

CHANTS = [
    ("1", "RENDONS, RENDONS GLOIRE"),
    ("2", "POUR CET IMMENSE BONHEUR"),
    ("3", "HYMNE DU RENOUVEAU / JESUS T'APPELLE"),
    ("4", "ICI NOUS NOUS SOMMES RENCONTRES"),
    ("5", "JESUS T'APPELLE"),
    ("6", "BENI SOIT DIEU"),
    ("7", "DIEU DIT A ABRAHAM"),
    ("8", "OU SERAS-TU QUAND JESUS REVIENDRA ?"),
    ("9", "JE SERVIRAI L'ETERNEL"),
    ("10", "LOUONS YAHVE"),
    ("11", "ECOUTEZ LA VOIX DU PROPHETE"),
    ("12", "VIE ASSOMBRIE"),
    ("13", "PRIERE D'ABRAHAM"),
    ("14", "AH YE ! AH YE ! ALLELUIA"),
    ("15", "NOUS MARCHONS VERS TA MAISON"),
    ("16", "NOUS VOULONS UN ROI"),
    ("17", "LES VINGT-SEPT LIVRES DU NT"),
    ("18", "SOYONS LE SEL ET LA LUMIERE (Mt 5,13-16)"),
    ("18 BIS", "QUELQU'UN FRAPPE A TA PORTE"),
    ("19", "SI DIEU NE NOUS AIMAIT PAS"),
    ("20", "TOUT EST FAIT POUR LA GLOIRE DE DIEU"),
    ("21", "TENTATION DE JESUS"),
    ("22", "GARDE-TOI D'OUBLIER LE SEIGNEUR TON DIEU"),
    ("23", "EN LUI NOUS AVONS LA VIE"),
    ("24", "TA PAROLE EST VIVANTE"),
    ("25", "LOUONS YAHVE, BENISSONS SON NOM"),
    ("26", "DEVANT TOI SEIGNEUR"),
    ("27", "DO LORD"),
    ("28", "LA SAINTE BIBLE"),
    ("29", "WE SHALL OVERCOME"),
    ("30", "QUE FERA LE JEUNE HOMME ?"),
    ("31", "L'ENFANT DE NUIT"),
    ("32", "ECOUTE MON AMI"),
    ("33", "EUE AU CARMEL"),
    ("34", "LES SEPT MIRACLES"),
    ("35", "L'ENTRETIEN DE L'ENFANT"),
    ("36", "MARDOCHEE"),
    ("37", "POURQUOI CE TUMULTE ?"),
    ("38", "PENSE A MOI SEIGNEUR"),
    ("39", "CHANTERAI TON NOM"),
    ("40", "DE MA VOIX JE CRIE A DIEU"),
    ("41", "L'ETERNEL A VU LES SOUFFRANCES"),
    ("42", "CONSECRATION"),
    ("43", "QUI PEUT GRAVIR LA MONTAGNE DE DIEU ?"),
    ("44", "LA SAMARITAINE"),
    ("45", "CHRIST EST NE"),
    ("46", "EYA EYA EYA EYA"),
    ("47", "ALLELUIA !"),
    ("48", "IL EST NE AUJOURD'HUI"),
    ("49", "JESUS-CHRIST EST NE"),
    ("50", "UN SAUVEUR NOUS EST NE"),
    ("51", "LES ANGES DANS NOS CAMPAGNES"),
    ("52", "QUE TOUT SE TAISE"),
    ("53", "LA CLOCHE A SONNE MES FRERES"),
    ("54", "VOICI NOEL ALLELUIA"),
    ("55", "UN SAUVEUR NOUS EST NE"),
    ("56", "VENEZ CHANTER A L'ETERNEL"),
    ("57", "UN FILS NOUS EST DONNE"),
    ("58", "LA BONNE NOUVELLE RETENTIT"),
    ("59", "L'ENFANT EST VENU / O DIEU TU ES PUISSANT"),
    ("60", "NOEL"),
    ("61", "CETTE NUIT-LA"),
    ("62", "ALLONS EN GALILEE / LE MESSIE PROMIS ET ATTEND"),
    ("63", "FRERES, JESUS VIENT DE NAITRE"),
    ("64", "JESUS ARTISAN DE PAIX"),
    ("65", "HOSANNA"),
    ("66", "L'HUMANITE VIT DANS LES TENEBRES"),
    ("67", "ALLELUIA ! IL EST NE LE ROI DES ROIS"),
    ("68", "LOUONS LE ROI DE GLOIRE"),
    ("69", "ELOI ! ELOI ! (Psaume 22)"),
    ("70", "JESUS DOIT MOURIR"),
    ("71", "JESUS MIT LE COMBLE A SON AMOUR"),
    ("72", "SUR LE CHEMIN DU CALVAIRE"),
    ("73", "JESUS A SOUFFERT"),
    ("74", "LE SEIGNEUR AU BOIS"),
    ("75", "L'HEURE DE LA MORT DE JESUS EST VENUE"),
    ("76", "JESUS EST RESSUSCITE"),
    ("77", "JESUS EST VIVANT"),
    ("78", "JESUS EST RESSUSCITE AUJOURD'HUI"),
    ("79", "QUI N'A PAS VU LE CHRIST"),
    ("80", "JESUS MON ROI EST RESSUSCITE"),
    ("81", "LE CHRIST EST VIVANT"),
    ("82", "C'EST UN NOUVEAU TEMPS"),
    ("83", "JESUS-CHRIST EST RESSUSCITE"),
    ("84", "ALLONS EN GALILEE (Mt 28,1-10)"),
    ("85", "JESUS EST RESSUSCITE"),
    ("86", "ALLELUIA ! BALAFONS, TAM-TAM"),
    ("87", "LA VERITE"),
    ("88", "PENSE A MOI SEIGNEUR"),
    ("89", "LA CONVERSION DE PAUL"),
    ("90", "O ! SEIGNEUR JESUS ME VOICI"),
    ("91", "SAUL EST CONVERTI"),
    ("92", "TEMOINS DE JESUS-CHRIST EN AFRIQUE"),
    ("93", "BENIS-NOUS SEIGNEUR"),
    ("94", "JESUS-CHRIST EST MA VIE"),
    ("95", "AH ! SEIGNEUR QUI ES-TU ?"),
    ("96", "PARDONNE-MOI SEIGNEUR !"),
    ("97", "JESUS AIME / O SEIGNEUR EXAUCE-NOUS"),
    ("98", "ET UNIT"),
    ("99", "DANS MON COEUR"),
    ("100", "RENDEZ GRACE A YAHVE"),
    ("101", "QUE FERAI-JE POUR TOI"),
    ("102", "CONNAISSEZ-VOUS JESUS-CHRIST ?"),
    ("103", "JE LE DIS EN VERITE"),
    ("104", "VENEZ AMIS"),
    ("105", "IL REVIENT BIENTOT"),
    ("106", "SEIGNEUR A QUI D'AUTRE IRONS-NOUS ?"),
    ("107", "JESUS ROIS DES ROIS"),
    ("108", "LE RESSUSCITE AGIT"),
    ("109", "L'AMOUR DE DIEU"),
    ("110", "JESUS EST MON SAUVEUR"),
    ("111", "AU COMMENCEMENT ETAIT LA PAROLE"),
    ("112", "JE SAIS QUE JE SUIS SAUVE"),
    ("113", "JESUS LE PAIN DE LA VIE"),
    ("114", "MERCI MON DIEU"),
    ("115", "J'IRAI LOUER L'ETERNEL"),
    ("116", "POUR TE DIRE MERCI"),
    ("117", "TOUT POUR LE SEIGNEUR"),
    ("118", "ENFANTS DONNONS"),
    ("119", "C'EST MON JOYEUX SERVICE"),
    ("120", "TOUT CE QUE NOUS AVONS"),
    ("121", "J'APPORTE AU SEIGNEUR MON OFFRANDE"),
    ("122", "VOICI MON DON"),
    ("123", "JESUS LA LUMIERE"),
    ("124", "LIT TA BIBLE"),
    ("125", "DIEU EST AMOUR"),
    ("126", "LEVE-TOI ET MARCHE"),
    ("127", "C'EST LE JOUR DU SEIGNEUR"),
    ("128", "O SEIGNEUR, AIE PITIE DE MOI"),
    ("129", "O CROIRE EN JESUS"),
    ("130", "PITIE MON DIEU PITIE"),
    ("131", "L'ETERNEL EST MON BERGER (Ps 23)"),
    ("132", "VIENS A JESUS TOUT PETIT ENFANT"),
    ("133", "VENEZ LOUEZ L'ETERNEL"),
    ("134", "NOUS NE SOMMES PAS TRISTES"),
    ("135", "JE SUIS FAIBLE"),
    ("136", "JESUS, JE T'AIME"),
    ("137", "DEVANT TOI SEIGNEUR"),
    ("138", "JE M'ENGAGE"),
    ("139", "ENGAGEONS-NOUS"),
    ("140", "JE VEUX SERVIR LE SEIGNEUR"),
    ("141", "ME VOICI AIE PITIE DE MOI"),
    ("142", "SEIGNEUR AIE PITIE"),
    ("143", "VIENS ET ASSISTE-NOUS"),
    ("144", "VOICI LA LOI DE YAHVE"),
    ("145", "SEIGNEUR JE VIENS VERS TOI"),
    ("146", "PRIONS DIEU, NOTRE PERE"),
    ("147", "TOUS ONT PECHE"),
    ("148", "LAISSEZ TOUS LES ENFANTS VENIR A MOI"),
    ("149", "HOMME SORT DE TA FAIBLESSE"),
    ("150", "GENESE, EXODE"),
    ("151", "CONFIE-TOI A DIEU"),
    ("152", "ENFANTS DE BANDJA"),
    ("153", "LA PAIX DANS L'AME"),
    ("154", "J'AI LA FOI"),
    ("155", "UN ENFANT NOUS EST NE"),
    ("156", "FETE DE NOEL !"),
    ("157", "AUJOURD'HUI JE SUIS NEE"),
    ("158", "JESUS A VAINCU LA MORT"),
    ("159", "O DIEU TU ES PUISSANT"),
    ("160", "ESPERER CONTRE TOUTE ESPERANCE"),
    ("161", "JE PASSERAI MA VIE"),
    ("162", "NE ME LAISSE PAS PERIR"),
    ("163", "AUJOURD'HUI C'EST NOEL"),
    ("164", "RIEN NE PEUT M'ARRACHER"),
    ("165", "OH ! VOUS QUI ETES EN CHRIST"),
    ("166", "PLUS LOIN DE TOI, O MON DIEU"),
    ("167", "TOUT NOTRE DON"),
    ("168", "IL VIT, IL VIT, IL VIT"),
    ("169", "JESUS-CHRIST NOUS T'IMPLORONS"),
    ("170", "VIE ASSOMBRIE"),
    ("171", "JE SUIS LE CHEMIN"),
    ("172", "MOI ET MA MAISON NOUS SERVIRONS L'ETERNEL"),
    ("173", "DIEU EST AMOUR"),
    ("174", "ACCLAMONS LE CHRIST / JE SUIS LE CHEMIN"),
    ("175", "PARLE, SEIGNEUR"),
    ("176", "TOUTE MA VIE, JE..."),
    ("177", "SOYONS SAINTS MES FRERES"),
    ("178", "LES MURS DE JERICHO SONT TOMBES"),
    ("179", "C'EST VRAI JESUS DONNE LA PAIX"),
    ("180", "MONITEURS TRAVAILLONS"),
    ("181", "QUI EST L'HOMME DE PAIX ?"),
    ("182", "RECHERCHE LA PAIX"),
    ("183", "LEVONS-NOUS SUIVONS TOUS JESUS"),
    ("184", "JESUS LE PACIFICATEUR"),
    ("185", "CHANTERAI TON NOM"),
    ("186", "JE CHANTE L'AMOUR DE MON DIEU"),
    ("187", "DONNE-NOUS SEIGNEUR"),
    ("188", "JE VEUX ALLER AU CIEL / TU M'AS VOULU COMME PARTENAIRE"),
    ("189", "JESUS-CHRIST EST LE SEIGNEUR"),
    ("190", "LE SEIGNEUR NOUS APPELLE"),
    ("191", "ENSEIGNE-NOUS A PRIER"),
    ("192", "C'EST BON DE LOUIR DIEU"),
    ("193", "TOUT CE QUE NOUS AVONS"),
    ("194", "NOUS SOMMES DES PETITS ENFANTS"),
    ("195", "JE SUIS PECHEUR"),
    ("196", "SAINT DES SAINTS EST L'ETERNEL"),
    ("197", "O SEIGNEUR EXAUCE-NOUS"),
    ("198", "JE VEUX ALLER AU CIEL"),
    ("199", "O ETERNEL DE LA PITIE"),
    ("200", "COME TO JESUS"),
    ("201", "QUI ETES-VOUS ?"),
    ("202", "VIENS A NOUS"),
    ("203", "EST-CE QUE TU CROIS ?"),
    ("204", "SEIGNEUR NOUS T'OFFRONS"),
    ("205", "IL EST BON DE TE CELEBRER"),
    ("206", "LE DOCTEUR DE MON COEUR"),
    ("207", "AUJOURD'HUI JESUS EST NE"),
    ("208", "REBATISSONS (Ne 2,18)"),
    ("209", "LEVONS-NOUS (Ne 2,18)"),
    ("210", "NE RESISTE PAS (Ne 3,12-19)"),
    ("211", "LEVONS-NOUS BATISSONS (Ne 2,18)"),
    ("212", "SOYONS SAINTS MES FRERES"),
    ("213", "LEVONS-NOUS ET BATISSONS"),
    ("214", "LEVONS-NOUS"),
    ("215", "AMOUR DE CHRIST"),
    ("216", "JE CONNAISSE BON CHEMIN"),
    ("217", "ALLELUIA JESUS-CHRIST EST NE"),
    ("218", "JESUS M'A LIBERE"),
    ("219", "JESUS EST RESSUSCITE"),
    ("220", "ENCHAINE DANS LA MISERE"),
]


def upgrade() -> None:
    op.create_table(
        "catalogue_chants",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("numero", sa.String(10), nullable=False),
        sa.Column("titre", sa.String(300), nullable=False),
    )
    op.bulk_insert(
        sa.table(
            "catalogue_chants",
            sa.column("numero", sa.String),
            sa.column("titre", sa.String),
        ),
        [{"numero": n, "titre": t} for n, t in CHANTS],
    )


def downgrade() -> None:
    op.drop_table("catalogue_chants")
